### ISSUE TITLE
cart item price increase as the quantity increases.

### ISSUE THREAD

**Issue by codersam10** [MohitSojitra/e-commerce-store#3]
How can i make increment in the cart item price here (shown in the image) as the quantity of a single cart item increases?

![Screenshot1](https://user-images.githubusercontent.com/97213565/235282953-1438c5d5-4b3d-44bc-9b77-2dcb276f954d.png)

**Comment by Yashpakar** [comment]
hey can you please help me with yarn command, I'm not able to yarn start the project it says the following error:
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MohitSojitra** [comment]
> How can i make increment in the cart item price here (shown in the image) as the quantity of a single cart item increases?
> 
> ![Screenshot1](https://user-images.githubusercontent.com/97213565/235282953-1438c5d5-4b3d-44bc-9b77-2dcb276f954d.png)


Regarding your question about incrementing the cart item price as the quantity of a single cart item increases, you can retrieve the item price from the redux store and use it to calculate the total price based on the quantity. I would suggest referring to the cartScreen.js file to see how the getCartSubTotal function works for more context.

However, I would also like to share my thoughts on this approach. Instead of updating the price to reflect the total amount, it might be better to display the single item price alongside the quantity. This will ensure that the user has a clear understanding of the cost of each individual item, and will avoid confusion if they come back to the cart page after a few days. This will provide a better user experience overall.

I hope this suggestion helps. Please let me know if you have any other questions or concerns.

Thanks.
