### ISSUE TITLE
Not able to yarn start 

### ISSUE THREAD

**Issue by Yashpakar** [MohitSojitra/e-commerce-store#4]
Did everything but yarn start is not working can anyone help my end sem project is really close it would be great if anyone would help me ASAP!
Error:
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\yashp\OneDrive\Desktop\mohit\e-commerce-store\e-comerce-frontend\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by codersam10** [comment]
run this command    $env:NODE_OPTIONS = "--openssl-legacy-provider"      on your powershell terminal in the frontend folder before you yarn start. let me know if it worked.

**Comment by Yashpakar** [comment]
Thank-you soo much it worked

**Comment by MohitSojitra** [comment]
Thank you @codersam10, I am also put this link on my readMe file. 

@codersam10 are you interested to create a Pr for that? Update the readme file with this link and description of this issue. Please let me know on here or Linkedin in 2 days, if you are interested otherwise I'll be updated.
